blank_issues_enabled: false
contact_links:
  - name: Get help
    url: https://github.com/leoviana00/GitContributionOpenSource/discussions/new?category=q-a
    about: Se você não conseguir que algo funcione da maneira esperada, abra uma pergunta em nossos fóruns de discussão.
  - name: Report a bug
    url: https://github.com/leoviana00/GitContributionOpenSource/discussions/new?category=bugs
    about: Se algo estiver quebrado no próprio projeto, crie um relatório de bug em nossos fóruns.