name: "PR Title Checker"
on:
  pull_request_target:
    types:
      - opened
      - edited
      - synchronize

jobs:
  validate-and-comment:
    permissions: write-all
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code from PR (Safe Checkout)
        uses: actions/checkout@v4
        with:
          ref: ${{ github.event.pull_request.head.sha }}

      - name: Validate PR
        uses: leoviana00/GitTemplate
        with:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          remote_configuration_path: "https://raw.githubusercontent.com/leoviana00/GitTemplate/main/.github/pr-title-checker-config.json"

      - name: Comment PR on Success and Add Label [automerge]
        if: success()
        run: |
          REPO_URL=${{ github.event.pull_request.head.repo.html_url }}
          cat <<EOT > message.txt
          Aí sim hein `${{ github.event.pull_request.user.login }}` ! Seu PR foi aprovado 🥳 
          Faremos o merge aqui em breve. Muito obrigado pela contribuição 🚀
          EOT

          gh pr comment ${{ github.event.pull_request.number }} --body-file=message.txt
          gh pr edit ${{ github.event.pull_request.number }} --add-label "automerge"
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Comment PR on Failure
        if: failure()
        run: |
          cat <<EOT > message.txt
          Olá `${{ github.event.pull_request.user.login }}`! Parece que houve um problema com o seu PR 🧐 Aqui estão algumas coisas para verificar:
          - Seu PR deve seguir a convenção de commits.

          Para obter mais detalhes e garantir que tudo esteja correto, confira nossas instruções nos arquivos [Guia do Contribuidor](https://github.com/leoviana00/GitTemplate/blob/main/CONTRIBUTING.md) (que, em geral, NÃO devem ser modificados, pois são arquivos genéricos de apoio).

          Se o seu PR tem um objetivo diferente, não se preocupe! Ele será analisado manualmente por nossa equipe, o que pode levar um pouco mais de tempo. Pedimos paciência nesse processo 🙏

          Agradecemos sua contribuição e compreensão 👊😉
          EOT

          gh pr comment ${{ github.event.pull_request.number }} --body-file=message.txt
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}

  
  automerge:
    runs-on: ubuntu-latest
    needs: validate-and-comment
    permissions:
      contents: write
    steps:
      - id: automerge
        name: automerge
        uses: "pascalgn/automerge-action@v0.16.3"
        env:
          GITHUB_TOKEN: "${{ secrets.GITHUB_TOKEN }}"